ProjektAJ/urls.py
from django.conf.urls import url
from . import views

app_name = 'ProjektAJ'

urlpatterns = [

    # /ProjektAJ/
    url(r'^$', views.IndexView.as_view(), name='index'),

    # /ProjektAJ/<album_id>/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    # /ProjektAJ/album/add/
    url(r'album/add/$', views.AlbumCreate.as_view(), name='album-add'),

    # /ProjektAJ/album/2/
    url(r'album/(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(), name='album-update'),

    # /ProjektAJ/album/2/delete/
    url(r'album/(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(), name='album-delete'),

    # /ProjektAJ/register/
    url(r'^register/$', views.UserFormView.as_view(), name='register'),

    # /ProjektAJ/song/add/
    url(r'song/add/$', views.SongCreate.as_view(), name='song-add'),

    # /ProjektAJ/songs/
    url(r'^songs/(?P<filter_by>[a-zA_Z]+)/$', views.SongsView.as_view(), name='songs'),

    # /ProjektAJ/photo/add/
    url(r'photo/add/$', views.PhotoCreate.as_view(), name='photo-add'),

    # /ProjektAJ/search/
    url(r'^search/$', views.searchview, name='search'),

    # /ProjektAJ/<album_id>/
    url(r'^(?P<album_id>[0-9]+)/$', views.detail, name='detail'),

    # /ProjektAJ/<song_id>/favorite
    url(r'^(?P<song_id>[0-9]+)/favorite/$', views.favorite, name='favorite'),

]

djangoAJ/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    path('ProjektAJ/', include('ProjektAJ.urls')),
]

if settings.DEBUG:
    urlpatterns += [ url(r'^media/(?P<path>.*)$', serve, { 'document_root': settings.MEDIA_ROOT, }), ]

ProjektAJ/models.py
from django.db import models
from django.urls import reverse


class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.FileField()

    def get_absolute_url(self):
        return reverse('ProjektAJ:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.album_title + ' - ' + self.artist


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    audio_file = models.FileField(default='')
    is_favorite = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('ProjektAJ:index')

    def __str__(self):
        return self.song_title

    @property
    def audio_url(self):
        if self.audio_file and hasattr(self.audio_file, 'url'):
            return self.audio_file.url


class Photo(models.Model):
    photo_album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    photo_title = models.CharField(max_length=250)
    photo = models.FileField()
    is_favorite = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('ProjektAJ:index')

    def __str__(self):
        return self.photo_title

companies/models.py
from django.db import models

# Create your models here.

class Stock(models.Model):
    ticker = models.CharField(max_length=10)
    open = models.FloatField()
    close = models.FloatField()
    volume = models.IntegerField()

    def __str__(self):
        return self.ticker

ProjektAJ/forms.py
from django.contrib.auth.models import User
from django import forms


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

ProjektAJ/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login
from django.urls import reverse_lazy
from django.views.generic import View
from .models import Album, Song, Photo
from .forms import UserForm
from django.db.models import Q
from django.http import JsonResponse


class IndexView(generic.ListView):
    template_name = 'ProjektAJ/index.html'
    context_object_name = 'all_albums'

    def get_queryset(self):
        return Album.objects.all()


class DetailView(generic.DetailView):
    model = Album
    template_name = 'ProjektAJ/detail.html'


class AlbumCreate(CreateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']


class AlbumUpdate(UpdateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']


class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('ProjektAJ:index')


class SongCreate(CreateView):
    model = Song
    fields = ['album', 'file_type', 'song_title', 'audio_file', 'is_favorite']


class SongUpdate(UpdateView):
    model = Song
    fields = ['album', 'file_type', 'song_title', 'audio_file', 'is_favorite']


class SongDelete(DeleteView):
    model = Song
    fields = ['album', 'file_type', 'song_title', 'audio_file', 'is_favorite']


class PhotoCreate(CreateView):
    model = Photo
    fields = ['photo_album', 'file_type', 'photo_title', 'photo', 'is_favorite']


class PhotoUpdate(UpdateView):
    model = Photo
    fields = ['photo_album', 'file_type', 'photo_title', 'photo', 'is_favorite']


class PhotoDelete(DeleteView):
    model = Photo
    fields = ['photo_album', 'file_type', 'photo_title', 'photo', 'is_favorite']


class SongsView(generic.ListView):
    template_name = 'ProjektAJ/songs.html'
    context_object_name = 'all_songs'

    def get_queryset(self):
        return Song.objects.all()


class UserFormView(View):
    form_class = UserForm
    template_name = 'ProjektAJ/registration_form.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():

            user = form.save(commit=False)

            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            user = authenticate(username=username, password=password)

            if user is not None:

                if user.is_active:
                    login(request,user)
                    return redirect('ProjektAJ:index')

        return render(request, self.template_name, {'form': form})


#def songs(request):
#        users_songs = Song.objects.all()
#
#        return render(request, 'ProjektAJ/songs.html', {
#            'song_list': users_songs,
#        })


def searchview(request):
        albums = Album.objects.all()
#        song_results = Album.objects.all()
        query = request.GET.get("q")
        albums = albums.filter(
            Q(album_title__icontains=query) |
            Q(artist__icontains=query)
        ).distinct()
#        song_results = song_results.filter(
#            Q(song_title__icontains=query)
#        ).distinct()
        return render(request, 'ProjektAJ/search.html', {
            'albums': albums,
        })


def detail(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    return render(request, 'ProjektAJ/detail.html', {'album': album})


def favorite(request, song_id):
    song = get_object_or_404(Song, pk=song_id)
    try:
        if song.is_favorite:
            song.is_favorite = False
        else:
            song.is_favorite = True
        song.save()
    except (KeyError, Song.DoesNotExist):
        return JsonResponse({'success': False})
    else:
        return JsonResponse({'success': True})

companies/views.py
from django.shortcuts import render

# Create your views here.

ProjektAJ/templates/ProjektAJ/album_form.html
{% extends 'ProjektAJ/base.html' %}
{% block title %}Szczegóły albumu{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">

                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'ProjektAJ/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Wyślij</button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>

    </div>

</div>
{% endblock %}

ProjektAJ/templates/ProjektAJ/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Django AJ{% endblock %}</title>
{% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="{% static 'ProjektAJ/style.css' %}" />
<link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet" type="text/css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!-- Naglowek -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'ProjektAJ:index' %}">Projekt na zaliczenie</a>
        </div>

        <!-- reszta -->
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{% url 'ProjektAJ:index' %}">
                        <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Albumy
                    </a>
                </li>
                <li class="{% block songs_active %}{% endblock %}">
                    <a href="{% url 'ProjektAJ:songs' 'all' %}">
                        <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; Piosenki
                    </a>
                </li>
            </ul>

            <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'ProjektAJ:search' %}">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                </div>
                <button type="submit" class="btn btn-default">Szukaj</button>
            </form>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="{% url 'ProjektAJ:photo-add' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Dodaj zdjęcie
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'ProjektAJ:song-add' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Dodaj piosenkę
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'ProjektAJ:album-add' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Dodaj album
                    </a>
                </li>
                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Wyloguj się
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

ProjektAJ/templates/ProjektAJ/create_song.html
{% extends 'ProjektAJ/base.html' %}
{% block title %}Dodaj piosenkę{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                        <a href="{% url 'ProjektAJ:detail' album.id %}">
                            {% if album.album_logo %}
                                <img src="{{ album.album_logo.url }}" class="img-responsive">
                            {% else %}
                                <h3>Brak obrazka</h3>
                            {% endif %}
                        </a>
                    <h1>{{ album.album_title }} <small>{{ album.genre }}</small></h1>
                    <h2>{{ album.artist }}</h2>
                </div>
            </div>
        </div>

        <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation">
                    <a href="{% url 'ProjektAJ:detail' album.id %}">Zobacz wszystko</a>
                </li>
                <li role="presentation" class="active">
                    <a href="{% url 'ProjektAJ:create_song' album.id %}">Dodaj nową piosenkę</a>
                </li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Dodaj piosenke</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="hidden" name="album" value="{{ album }}">
                        {% include 'ProjektAJ/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Wyślij</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

ProjektAJ/templates/ProjektAJ/detail.html
{% extends 'ProjektAJ/base.html' %}
{% block title %}Szczegoly albumy{% endblock %}

{% block body %}
<div class="container-fluid songs-container">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'ProjektAJ:detail' album.id %}">
                        {% if album.album_logo %}
                            <img src="{{ album.album_logo.url }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h1>{{ album.album_title }} <small>{{ album.genre }}</small></h1>
                    <h2>{{ album.artist }}</h2>
                </div>
            </div>
        </div>

        <!-- Right Panel Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active">
                    <a href="{% url 'ProjektAJ:detail' album.id %}">Zobacz wszystko</a>
                </li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>Wszystkie Piosenki</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                 <table class="table">
                        <thead>
                        <tr>
                            <th>Tytuł</th>
                            <th>Plik audio</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for song in album.song_set.all %}
                            <tr>
                                <td>{{ song.song_title }}</td>
                                <td>
                                        <a target="_blank" href="{{ song.audio_url|default_if_none:'#' }}">
                                        <button type="button" class="btn btn-success btn-xs">
                                            <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                        </button>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                 <!--   <table class="table">
                        <thead>
                        <tr>
                            <th>Tytuł</th>
                            <th>Plik audio</th>
                            <th>Favorite</th>
                            <th>Akcja</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for photo in album.photo_set.all %}
                            <tr>
                                <td>{{ photo.photo_title }}</td>
                                <td>{{ photo.file_type }}</td>
                                <td><img src="{{ photo.photo.url }}" class="img-responsive"></td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table> -->
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Galeria zdjęć</h3>
                    <div class="container">
                        <div class="row" id="efekt">
                        {% for photo in album.photo_set.all %}
                            <div class="col-md-3 col-sm-4 col-xs-6">
                                <img class="img-responsive" src="{{ photo.photo.url }}" />
                            </div>
                        {% endfor %}
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>

</div>

{% endblock %}

ProjektAJ/templates/ProjektAJ/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

ProjektAJ/templates/ProjektAJ/index.html
<!-- Zaladowanie sciezko dla plikow statycznych -->
{% extends 'ProjektAJ/base.html' %}

{% block body %}

    <ul>
        {% for album in all_albums %}


            <div class="col-sm-4 col-lg-2">
                <div class="thumbnail">
                    <a href="{% url 'ProjektAJ:detail' album.id %}">
                        <img src="{{ album.album_logo.url }}" class="img-responsive">
                    </a>
                    <div class="caption">
                        <h2>{{ album.album_title }}</h2>
                        <h4>{{ album.artist }}</h4>

                        <!-- View Details -->
                        <a href="{% url 'ProjektAJ:detail' album.id %}" class="btn btn-primary btn-sm" role="button">Szczegóły</a>

                        <!-- Edit Album -->
                        <form action="{% url 'ProjektAJ:album-update' album.id %}" method="get" style="display: inline;">
                            {% csrf_token %}
                            <input type="hidden" name="album_id" value="{{ album.id }}" />
                            <button type="submit" class="btn btn-default btn-sm">
                                <span class="glyphicon glyphicon-pencil"></span>
                            </button>
                        </form>

                        <!-- Delete Album -->
                        <form action="{% url 'ProjektAJ:album-delete' album.id %}" method="post" style="display: inline;">
                            {% csrf_token %}
                            <input type="hidden" name="album_id" value="{{ album.id }}" />
                            <button type="submit" class="btn btn-default btn-sm">
                                <span class="glyphicon glyphicon-trash"></span>
                            </button>
                        </form>

                    </div>
                </div>
            </div>
            {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
        {% endfor %}
    </ul>

{% endblock %}

ProjektAJ/templates/ProjektAJ/photo_form.html
{% extends 'ProjektAJ/base.html' %}
{% block title %}Dodaj Zdjecie{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">

                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'ProjektAJ/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Wyslij</button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>

    </div>

</div>
{% endblock %}

ProjektAJ/templates/ProjektAJ/registration_form.html
{% extends 'ProjektAJ/base.html' %}
{% block title %}Register{% endblock %}
{% block register_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Register for an Account</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'ProjektAJ/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

ProjektAJ/templates/ProjektAJ/search.html
{% extends 'ProjektAJ/base.html' %}
{% block title %}Rezultat{% endblock %}
{% block songs_active %}active{% endblock %}


{% block body %}

    <ul>
        {% for album in albums %}


            <div class="col-sm-4 col-lg-2">
                <div class="thumbnail">
                    <a href="{% url 'ProjektAJ:detail' album.id %}">
                        <img src="{{ album.album_logo.url }}" class="img-responsive">
                    </a>
                    <div class="caption">
                        <h2>{{ album.album_title }}</h2>
                        <h4>{{ album.artist }}</h4>

                        <!-- View Details -->
                        <a href="{% url 'ProjektAJ:detail' album.id %}" class="btn btn-primary btn-sm" role="button">Szczegoly</a>

                        <!-- Edit Album -->
                        <form action="{% url 'ProjektAJ:album-update' album.id %}" method="get" style="display: inline;">
                            {% csrf_token %}
                            <input type="hidden" name="album_id" value="{{ album.id }}" />
                            <button type="submit" class="btn btn-default btn-sm">
                                <span class="glyphicon glyphicon-pencil"></span>
                            </button>
                        </form>

                        <!-- Delete Album -->
                        <form action="{% url 'ProjektAJ:album-delete' album.id %}" method="post" style="display: inline;">
                            {% csrf_token %}
                            <input type="hidden" name="album_id" value="{{ album.id }}" />
                            <button type="submit" class="btn btn-default btn-sm">
                                <span class="glyphicon glyphicon-trash"></span>
                            </button>
                        </form>

                    </div>
                </div>
            </div>
            {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
        {% endfor %}
    </ul>

{% endblock %}

ProjektAJ/templates/ProjektAJ/song_form.html
{% extends 'ProjektAJ/base.html' %}
{% block title %}Dodaj Piosenke{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">

                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'ProjektAJ/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Wyslij</button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>

    </div>

</div>
{% endblock %}

ProjektAJ/templates/ProjektAJ/songs.html
{% extends 'ProjektAJ/base.html' %}
{% block title %}Wszystkie piosenki{% endblock %}
{% block songs_active %}active{% endblock %}

{% block body %}
 <div class="container-fluid songs-container">
    <div class="row">

        <div class="col-sm-12">

            <div class="panel panel-default">
                <div class="panel-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Song Title</th>
                                <th>Artist</th>
                                <th>Audio File</th>
                                <th>Album</th>
                                <th>Favorite</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for song in all_songs %}
                               <tr>
                                  <td>{{ song.song_title }}</td>
                                  <td>{{ song.album.artist }}</td>
                                  <td>
                                      <a target="_blank" href="{{ song.audio_url|default_if_none:'#' }}">
                                          <button type="button" class="btn btn-success btn-xs">
                                              <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                          </button>
                                      </a>
                                  </td>
                                  <td>
                                     <a href="{% url 'ProjektAJ:detail' song.album.id %}">
                                         <img src="{{ song.album.album_logo.url }}" class="img-responsive" style="width: 20px; float: left; margin-right: 10px;" />
                                     </a>
                                     <a href="{% url 'ProjektAJ:detail' song.album.id %}">{{ song.album.album_title }}</a>
                                  </td>
                                  <td>
                                      <a href="{% url 'ProjektAJ:favorite' song.id %}" class="btn-favorite">
                                          <span class="glyphicon glyphicon-star {% if song.is_favorite %}active{% endif %}"></span>
                                      </a>
                                  </td>
                               </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>

        </div>
</div>
{% endblock %}